services:

  client:
    build: ./client
    container_name: client
    ports:
      - 5173:5173
    restart: always
    volumes:
      - ./client:/client
    networks:
      - dev

  server:
    build: ./server
    container_name: server
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/server
    networks:
      - dev

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - dev

networks:

  dev:
    driver: bridge

volumes:

  postgres_data:
  redis_data:
